---
- name: Install certbot and dependencies (CentOS)
  package:
    name:
      - epel-release
      - certbot
      - python3-certbot-apache
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure Apache is installed
  package:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"

- name: Generate self-signed SSL certificates
  copy:
    content: |
      [ req ]
      default_bits        = 2048
      default_md          = sha256
      prompt              = no
      distinguished_name  = dn

      [ dn ]
      C                   = US
      ST                  = California
      L                   = San Francisco
      O                   = Example
      OU                  = Example
      CN                  = {{ item.server_name }}

      [ ext ]
      subjectAltName      = @alt_names

      [ alt_names ]
      DNS.1               = {{ item.server_name }}
    dest: "/etc/pki/tls/certs/{{ item.server_name }}.crt"
  with_items: "{{ virtual_hosts }}"

- name: Configure HTTPS virtual hosts using self-signed certificates
  template:
    src: ssl_virtualhost.conf.j2
    dest: "/etc/httpd/conf.d/{{ item.server_name }}.conf"
  with_items: "{{ virtual_hosts }}"
  notify: Restart httpd

- name: Enable SSL module for Apache (CentOS)
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^#?LoadModule ssl_module modules/mod_ssl.so'
    line: 'LoadModule ssl_module modules/mod_ssl.so'
  notify: Restart httpd
  when: ansible_os_family == 'RedHat'

- name: Enable SSL module for Apache (Ubuntu)
  command: a2enmod ssl
  notify: Restart httpd
  when: ansible_os_family == 'Debian'

